server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.foodhub.customer: DEBUG

grpc:
  server:
    port: 9090    

graphql:
  servlet:
    mapping: /graphql
    enabled: true
  graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true